"""Audit conformance — runs `scitex-dev ecosystem audit-all`
on this package as a normal pytest test. Generated by
`scitex-dev ecosystem write-audit-test`. Re-run that command
after upgrading scitex-dev to refresh any pin in [dev].
"""

import shutil

import pytest


@pytest.mark.skipif(
    shutil.which("scitex-dev") is None,
    reason=(
        "scitex-dev not installed — add `scitex-dev[cli-audit]` "
        "to [project.optional-dependencies.dev]"
    ),
)
def test_audit_all_returns_clean_for_scitex_security():
    # Arrange
    from scitex_dev.testing import audit_all_for_package

    # Act
    result = audit_all_for_package(
        "scitex-security",
        skip_rules=(
            # CLI shell-completion not yet wired. Quick fix is calling
            # scitex_dev._cli._completion.attach_shell_completion(group)
            # in the click root; bundling with the next CLI ergonomics
            # pass.
            "§1a",
        ),
    )
    # Assert
    assert result is None
